{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provider-tailscale.secretName" . }}
  namespace: {{ .Values.secret.namespace }}
  labels:
    {{- include "provider-tailscale.labels" . | nindent 4 }}
  annotations:
    {{- include "provider-tailscale.annotations" (dict "root" . "syncWave" .Values.syncWave.secret) | nindent 4 }}
type: Opaque
{{- if .Values.secret.apiKey }}
data:
  api_key: {{ .Values.secret.apiKey | b64enc | quote }}
{{- end }}
{{- end }}
